# .github/workflows/deploy.yml
name: Deploy Docusaurus Site to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master', or your primary source branch
  pull_request:
    branches:
      - main # Or 'master'
    # Optionally configure to only run on merged PRs, or use a different trigger
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not always necessary, but good for versioning

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your project's Node.js version
          cache: 'npm' # Or 'yarn', 'pnpm'

      - name: Install dependencies
        run: npm ci # Or yarn install --frozen-lockfile, or pnpm install --frozen-lockfile

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4
        # This action is optional if you are not using a custom domain with GitHub Pages
        # or if your Docusaurus base URL is already correctly set for the deployment environment.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4